# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - click
          - click_extra
          - sqlmodel
          - pydantic
          - types-pywin32
          - types-python-dateutil
          - pytest
          - pytest-asyncio
          - pytest-mock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff-check
        args: [--show-fixes]
      - id: ruff-format
        args: [--diff]

fail_fast: true
