# For the available values, see
# https://github.com/obbimi/Squore/blob/master/src/com/doubleyellow/scoreboard/prefs/ShareMatchPrefs.java
# LinkWithFullDetails, Summary, SummaryMultiple, SummaryToDefault, PostResult, SheetInEmail
shareAction = "PostResult"

# If shareAction == "PostResult", the URL where to POST the results.
# If specified as a relative URL, the same scheme/host/port will be used to which the client
# send the request.
# TODO: interaction with MQTT?
PostResult = "/tptools/v1/squore/result"

# What to POST to the URL:
# https://github.com/obbimi/Squore/blob/master/src/com/doubleyellow/scoreboard/prefs/PostDataPreference.java
# Basic, BasicWithJsonDetails, JsonDetailsOnly
postDataPreference = "JsonDetailsOnly"

# Message to prompt the user prior to results submission
captionForPostMatchResultToSite = "Submit match result to tournament control"

autoSuggestToPostResult = true

LiveScoreUrl = ""                          #TODO: what to put here?
turnOnLiveScoringForMatchesFromFeed = true
postEveryChangeToSupportLiveScore = true

hideCompletedMatchesFromFeed = true

Placeholder_Match = "${draw.event} @ ${time} : ${FirstOfList:~${A}~${A.name}~} vs. ${FirstOfList:~${B}~${B.name}~} (${id})"

skipMatchSettings = true
useHandInHandOutScoring = false
numberOfPointsToWinGame = 11
numberOfGamesToWinMatch = 3
timerPauseBetweenGames = 120

# For the available values, see
# https://github.com/obbimi/Squore/blob/master/src/com/doubleyellow/scoreboard/model/TieBreakFormat.java
# TwoClearPoints, SelectOneOrTwo, SelectOneTwoOrThree, SelectOneOrThree, SuddenDeath
tieBreakFormat = "TwoClearPoints"
