name: Style and unit tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . .[dev]
      - name: Style and formatting (ruff)
        run: |
          ruff check .
      - name: Unit and integration tests (pytest)
        run: |
          pytest
      - name: Mypy Check
        uses: jpetrucciani/mypy-check@master
        with:
          python_version: "3.13"
          requirements: ". .[dev]"
