name: Build package

on:
  push:
    tags: ["v*"]
  workflow_dispatch: # allows manual triggering

jobs:
  build:
    name: "Build package"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Python 3.x
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install build tool
        run: python -m pip install build

      - name: Build package
        run: python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
